<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Municipality;

class MunicipalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipality::insert([
            [
                "id" => 1,
                "municipality_name" => "Ahuachapán",
                "mun_min" => "Ahuachapan",
                "mun_may" => "AHUACHAPAN",
                "dm_cod" => "0101",
                "cod_mun" => "01",
                "department_id" => 1,
            ],
            [
                "id" => 11,
                "municipality_name" => "Apaneca",
                "mun_min" => "Apaneca",
                "mun_may" => "APANECA",
                "dm_cod" => "0102",
                "cod_mun" => "02",
                "department_id" => 1,
            ],
            [
                "id" => 26,
                "municipality_name" => "Atiquizaya",
                "mun_min" => "Atiquizaya",
                "mun_may" => "ATIQUIZAYA",
                "dm_cod" => "0103",
                "cod_mun" => "03",
                "department_id" => 1,
            ],
            [
                "id" => 13,
                "municipality_name" => "Concepción de Ataco",
                "mun_min" => "Concepcion de Ataco",
                "mun_may" => "CONCEPCION DE ATACO",
                "dm_cod" => "0104",
                "cod_mun" => "04",
                "department_id" => 1,
            ],
            [
                "id" => 28,
                "municipality_name" => "El Refugio",
                "mun_min" => "El Refugio",
                "mun_may" => "EL REFUGIO",
                "dm_cod" => "0105",
                "cod_mun" => "05",
                "department_id" => 1,
            ],
            [
                "id" => 23,
                "municipality_name" => "Guaymango",
                "mun_min" => "Guaymango",
                "mun_may" => "GUAYMANGO",
                "dm_cod" => "0106",
                "cod_mun" => "06",
                "department_id" => 1,
            ],
            [
                "id" => 37,
                "municipality_name" => "Jujutla",
                "mun_min" => "Jujutla",
                "mun_may" => "JUJUTLA",
                "dm_cod" => "0107",
                "cod_mun" => "07",
                "department_id" => 1,
            ],
            [
                "id" => 5,
                "municipality_name" => "San Francisco Menéndez",
                "mun_min" => "San Francisco Menendez",
                "mun_may" => "SAN FRANCISCO MENENDEZ",
                "dm_cod" => "0108",
                "cod_mun" => "08",
                "department_id" => 1,
            ],
            [
                "id" => 3,
                "municipality_name" => "San Lorenzo",
                "mun_min" => "San Lorenzo",
                "mun_may" => "SAN LORENZO",
                "dm_cod" => "0109",
                "cod_mun" => "09",
                "department_id" => 1,
            ],
            [
                "id" => 10,
                "municipality_name" => "San Pedro Puxtla",
                "mun_min" => "San Pedro Puxtla",
                "mun_may" => "SAN PEDRO PUXTLA",
                "dm_cod" => "0110",
                "cod_mun" => "10",
                "department_id" => 1,
            ],
            [
                "id" => 14,
                "municipality_name" => "Tacuba",
                "mun_min" => "Tacuba",
                "mun_may" => "TACUBA",
                "dm_cod" => "0111",
                "cod_mun" => "11",
                "department_id" => 1,
            ],
            [
                "id" => 63,
                "municipality_name" => "Turín",
                "mun_min" => "Turin",
                "mun_may" => "TURIN",
                "dm_cod" => "0112",
                "cod_mun" => "12",
                "department_id" => 1,
            ],
            [
                "id" => 64,
                "municipality_name" => "Candelaria de la Frontera",
                "mun_min" => "Candelaria de la Frontera",
                "mun_may" => "CANDELARIA DE LA FRONTERA",
                "dm_cod" => "0201",
                "cod_mun" => "01",
                "department_id" => 2,
            ],
            [
                "id" => 61,
                "municipality_name" => "Coatepeque",
                "mun_min" => "Coatepeque",
                "mun_may" => "COATEPEQUE",
                "dm_cod" => "0202",
                "cod_mun" => "02",
                "department_id" => 2,
            ],
            [
                "id" => 36,
                "municipality_name" => "Chalchuapa",
                "mun_min" => "Chalchuapa",
                "mun_may" => "CHALCHUAPA",
                "dm_cod" => "0203",
                "cod_mun" => "03",
                "department_id" => 2,
            ],
            [
                "id" => 75,
                "municipality_name" => "El Congo",
                "mun_min" => "El Congo",
                "mun_may" => "EL CONGO",
                "dm_cod" => "0204",
                "cod_mun" => "04",
                "department_id" => 2,
            ],
            [
                "id" => 68,
                "municipality_name" => "El Porvenir",
                "mun_min" => "El Porvenir",
                "mun_may" => "EL PORVENIR",
                "dm_cod" => "0205",
                "cod_mun" => "05",
                "department_id" => 2,
            ],
            [
                "id" => 70,
                "municipality_name" => "Masahuat",
                "mun_min" => "Masahuat",
                "mun_may" => "MASAHUAT",
                "dm_cod" => "0206",
                "cod_mun" => "06",
                "department_id" => 2,
            ],
            [
                "id" => 83,
                "municipality_name" => "Metapán",
                "mun_min" => "Metapan",
                "mun_may" => "METAPAN",
                "dm_cod" => "0207",
                "cod_mun" => "07",
                "department_id" => 2,
            ],
            [
                "id" => 49,
                "municipality_name" => "San Antonio Pajonal",
                "mun_min" => "San Antonio Pajonal",
                "mun_may" => "SAN ANTONIO PAJONAL",
                "dm_cod" => "0208",
                "cod_mun" => "08",
                "department_id" => 2,
            ],
            [
                "id" => 38,
                "municipality_name" => "San Sebastián Salitrillo",
                "mun_min" => "San Sebastian Salitrillo",
                "mun_may" => "SAN SEBASTIAN SALITRILLO",
                "dm_cod" => "0209",
                "cod_mun" => "09",
                "department_id" => 2,
            ],
            [
                "id" => 91,
                "municipality_name" => "Santa Ana",
                "mun_min" => "Santa Ana",
                "mun_may" => "SANTA ANA",
                "dm_cod" => "0210",
                "cod_mun" => "10",
                "department_id" => 2,
            ],
            [
                "id" => 88,
                "municipality_name" => "Santa Rosa Guachipilín",
                "mun_min" => "Santa Rosa Guachipilin",
                "mun_may" => "SANTA ROSA GUACHIPILIN",
                "dm_cod" => "0211",
                "cod_mun" => "11",
                "department_id" => 2,
            ],
            [
                "id" => 89,
                "municipality_name" => "Santiago de la Frontera",
                "mun_min" => "Santiago de la Frontera",
                "mun_may" => "SANTIAGO DE LA FRONTERA",
                "dm_cod" => "0212",
                "cod_mun" => "12",
                "department_id" => 2,
            ],
            [
                "id" => 90,
                "municipality_name" => "Texistepeque",
                "mun_min" => "Texistepeque",
                "mun_may" => "TEXISTEPEQUE",
                "dm_cod" => "0213",
                "cod_mun" => "13",
                "department_id" => 2,
            ],
            [
                "id" => 92,
                "municipality_name" => "Acajutla",
                "mun_min" => "Acajutla",
                "mun_may" => "ACAJUTLA",
                "dm_cod" => "0301",
                "cod_mun" => "01",
                "department_id" => 3,
            ],
            [
                "id" => 54,
                "municipality_name" => "Armenia",
                "mun_min" => "Armenia",
                "mun_may" => "ARMENIA",
                "dm_cod" => "0302",
                "cod_mun" => "02",
                "department_id" => 3,
            ],
            [
                "id" => 93,
                "municipality_name" => "Caluco",
                "mun_min" => "Caluco",
                "mun_may" => "CALUCO",
                "dm_cod" => "0303",
                "cod_mun" => "03",
                "department_id" => 3,
            ],
            [
                "id" => 19,
                "municipality_name" => "Cuisnahuat",
                "mun_min" => "Cuisnahuat",
                "mun_may" => "CUISNAHUAT",
                "dm_cod" => "0304",
                "cod_mun" => "04",
                "department_id" => 3,
            ],
            [
                "id" => 20,
                "municipality_name" => "Santa Isabel Ishuatán",
                "mun_min" => "Santa Isabel Ishuatan",
                "mun_may" => "SANTA ISABEL ISHUATAN",
                "dm_cod" => "0305",
                "cod_mun" => "05",
                "department_id" => 3,
            ],
            [
                "id" => 97,
                "municipality_name" => "Izalco",
                "mun_min" => "Izalco",
                "mun_may" => "IZALCO",
                "dm_cod" => "0306",
                "cod_mun" => "06",
                "department_id" => 3,
            ],
            [
                "id" => 98,
                "municipality_name" => "Juayúa",
                "mun_min" => "Juayua",
                "mun_may" => "JUAYUA",
                "dm_cod" => "0307",
                "cod_mun" => "07",
                "department_id" => 3,
            ],
            [
                "id" => 79,
                "municipality_name" => "Nahuizalco",
                "mun_min" => "Nahuizalco",
                "mun_may" => "NAHUIZALCO",
                "dm_cod" => "0308",
                "cod_mun" => "08",
                "department_id" => 3,
            ],
            [
                "id" => 220,
                "municipality_name" => "Nahulingo",
                "mun_min" => "Nahulingo",
                "mun_may" => "NAHULINGO",
                "dm_cod" => "0309",
                "cod_mun" => "09",
                "department_id" => 3,
            ],
            [
                "id" => 221,
                "municipality_name" => "Salcoatitán",
                "mun_min" => "Salcoatitan",
                "mun_may" => "SALCOATITAN",
                "dm_cod" => "0310",
                "cod_mun" => "10",
                "department_id" => 3,
            ],
            [
                "id" => 222,
                "municipality_name" => "San Antonio del Monte",
                "mun_min" => "San Antonio del Monte",
                "mun_may" => "SAN ANTONIO DEL MONTE",
                "dm_cod" => "0311",
                "cod_mun" => "11",
                "department_id" => 3,
            ],
            [
                "id" => 223,
                "municipality_name" => "San Julián",
                "mun_min" => "San Julian",
                "mun_may" => "SAN JULIAN",
                "dm_cod" => "0312",
                "cod_mun" => "12",
                "department_id" => 3,
            ],
            [
                "id" => 224,
                "municipality_name" => "Santa Catarina Masahuat",
                "mun_min" => "Santa Catarina Masahuat",
                "mun_may" => "SANTA CATARINA MASAHUAT",
                "dm_cod" => "0313",
                "cod_mun" => "13",
                "department_id" => 3,
            ],
            [
                "id" => 225,
                "municipality_name" => "#N/D",
                "mun_min" => "Santo Domingo de Guzman",
                "mun_may" => "SANTO DOMINGO DE GUZMAN",
                "dm_cod" => "0314",
                "cod_mun" => "14",
                "department_id" => 3,
            ],
            [
                "id" => 35,
                "municipality_name" => "Sonsonate",
                "mun_min" => "Sonsonate",
                "mun_may" => "SONSONATE",
                "dm_cod" => "0315",
                "cod_mun" => "15",
                "department_id" => 3,
            ],
            [
                "id" => 107,
                "municipality_name" => "Sonzacate",
                "mun_min" => "Sonzacate",
                "mun_may" => "SONZACATE",
                "dm_cod" => "0316",
                "cod_mun" => "16",
                "department_id" => 3,
            ],
            [
                "id" => 121,
                "municipality_name" => "Agua Caliente",
                "mun_min" => "Agua Caliente",
                "mun_may" => "AGUA CALIENTE",
                "dm_cod" => "0401",
                "cod_mun" => "01",
                "department_id" => 4,
            ],
            [
                "id" => 42,
                "municipality_name" => "Arcatao",
                "mun_min" => "Arcatao",
                "mun_may" => "ARCATAO",
                "dm_cod" => "0402",
                "cod_mun" => "02",
                "department_id" => 4,
            ],
            [
                "id" => 101,
                "municipality_name" => "Azacualpa",
                "mun_min" => "Azacualpa",
                "mun_may" => "AZACUALPA",
                "dm_cod" => "0403",
                "cod_mun" => "03",
                "department_id" => 4,
            ],
            [
                "id" => 8,
                "municipality_name" => "Citalá",
                "mun_min" => "Citala",
                "mun_may" => "CITALA",
                "dm_cod" => "0404",
                "cod_mun" => "04",
                "department_id" => 4,
            ],
            [
                "id" => 127,
                "municipality_name" => "Comalapa",
                "mun_min" => "Comalapa",
                "mun_may" => "COMALAPA",
                "dm_cod" => "0405",
                "cod_mun" => "05",
                "department_id" => 4,
            ],
            [
                "id" => 122,
                "municipality_name" => "Concepción Quezaltepeque",
                "mun_min" => "Concepcion Quezaltepeque",
                "mun_may" => "CONCEPCION QUEZALTEPEQUE",
                "dm_cod" => "0406",
                "cod_mun" => "06",
                "department_id" => 4,
            ],
            [
                "id" => 77,
                "municipality_name" => "Chalatenango",
                "mun_min" => "Chalatenango",
                "mun_may" => "CHALATENANGO",
                "dm_cod" => "0407",
                "cod_mun" => "07",
                "department_id" => 4,
            ],
            [
                "id" => 53,
                "municipality_name" => "Dulce Nombre de María",
                "mun_min" => "Dulce Nombre de Maria",
                "mun_may" => "DULCE NOMBRE DE MARIA",
                "dm_cod" => "0408",
                "cod_mun" => "08",
                "department_id" => 4,
            ],
            [
                "id" => 102,
                "municipality_name" => "El Carrizal",
                "mun_min" => "El Carrizal",
                "mun_may" => "EL CARRIZAL",
                "dm_cod" => "0409",
                "cod_mun" => "09",
                "department_id" => 4,
            ],
            [
                "id" => 50,
                "municipality_name" => "El Paraíso",
                "mun_min" => "El Paraiso",
                "mun_may" => "EL PARAISO",
                "dm_cod" => "0410",
                "cod_mun" => "10",
                "department_id" => 4,
            ],
            [
                "id" => 94,
                "municipality_name" => "La Laguna",
                "mun_min" => "La Laguna",
                "mun_may" => "LA LAGUNA",
                "dm_cod" => "0411",
                "cod_mun" => "11",
                "department_id" => 4,
            ],
            [
                "id" => 120,
                "municipality_name" => "La Palma",
                "mun_min" => "La Palma",
                "mun_may" => "LA PALMA",
                "dm_cod" => "0412",
                "cod_mun" => "12",
                "department_id" => 4,
            ],
            [
                "id" => 15,
                "municipality_name" => "La Reina",
                "mun_min" => "La Reina",
                "mun_may" => "LA REINA",
                "dm_cod" => "0413",
                "cod_mun" => "13",
                "department_id" => 4,
            ],
            [
                "id" => 231,
                "municipality_name" => "Las Vueltas",
                "mun_min" => "Las Vueltas",
                "mun_may" => "LAS VUELTAS",
                "dm_cod" => "0414",
                "cod_mun" => "14",
                "department_id" => 4,
            ],
            [
                "id" => 113,
                "municipality_name" => "Nombre de Jesús",
                "mun_min" => "Nombre de Jesus",
                "mun_may" => "NOMBRE DE JESUS",
                "dm_cod" => "0415",
                "cod_mun" => "15",
                "department_id" => 4,
            ],
            [
                "id" => 117,
                "municipality_name" => "Nueva Concepción",
                "mun_min" => "Nueva Concepcion",
                "mun_may" => "NUEVA CONCEPCION",
                "dm_cod" => "0416",
                "cod_mun" => "16",
                "department_id" => 4,
            ],
            [
                "id" => 40,
                "municipality_name" => "Nueva Trinidad",
                "mun_min" => "Nueva Trinidad",
                "mun_may" => "NUEVA TRINIDAD",
                "dm_cod" => "0417",
                "cod_mun" => "17",
                "department_id" => 4,
            ],
            [
                "id" => 233,
                "municipality_name" => "Ojos de Agua",
                "mun_min" => "Ojos de Agua",
                "mun_may" => "OJOS DE AGUA",
                "dm_cod" => "0418",
                "cod_mun" => "18",
                "department_id" => 4,
            ],
            [
                "id" => 65,
                "municipality_name" => "Potonico",
                "mun_min" => "Potonico",
                "mun_may" => "POTONICO",
                "dm_cod" => "0419",
                "cod_mun" => "19",
                "department_id" => 4,
            ],
            [
                "id" => 232,
                "municipality_name" => "San Antonio de la Cruz",
                "mun_min" => "San Antonio de la Cruz",
                "mun_may" => "SAN ANTONIO DE LA CRUZ",
                "dm_cod" => "0420",
                "cod_mun" => "20",
                "department_id" => 4,
            ],
            [
                "id" => 230,
                "municipality_name" => "San Antonio Los Ranchos",
                "mun_min" => "San Antonio los Ranchos",
                "mun_may" => "SAN ANTONIO LOS RANCHOS",
                "dm_cod" => "0421",
                "cod_mun" => "21",
                "department_id" => 4,
            ],
            [
                "id" => 123,
                "municipality_name" => "San Fernando",
                "mun_min" => "San Fernando",
                "mun_may" => "SAN FERNANDO",
                "dm_cod" => "0422",
                "cod_mun" => "22",
                "department_id" => 4,
            ],
            [
                "id" => 41,
                "municipality_name" => "San Francisco Lempa",
                "mun_min" => "San Francisco Lempa",
                "mun_may" => "SAN FRANCISCO LEMPA",
                "dm_cod" => "0423",
                "cod_mun" => "23",
                "department_id" => 4,
            ],
            [
                "id" => 119,
                "municipality_name" => "San Francisco Morazán",
                "mun_min" => "San Francisco Morazan",
                "mun_may" => "SAN FRANCISCO MORAZAN",
                "dm_cod" => "0424",
                "cod_mun" => "24",
                "department_id" => 4,
            ],
            [
                "id" => 217,
                "municipality_name" => "San Ignacio",
                "mun_min" => "San Ignacio",
                "mun_may" => "SAN IGNACIO",
                "dm_cod" => "0425",
                "cod_mun" => "25",
                "department_id" => 4,
            ],
            [
                "id" => 62,
                "municipality_name" => "San Isidro Labrador",
                "mun_min" => "San Isidro Labrador",
                "mun_may" => "SAN ISIDRO LABRADOR",
                "dm_cod" => "0426",
                "cod_mun" => "26",
                "department_id" => 4,
            ],
            [
                "id" => 124,
                "municipality_name" => "Cancasque",
                "mun_min" => "Cancasque",
                "mun_may" => "CANCASQUE",
                "dm_cod" => "0427",
                "cod_mun" => "27",
                "department_id" => 4,
            ],
            [
                "id" => 118,
                "municipality_name" => "Las Flores",
                "mun_min" => "Las Flores",
                "mun_may" => "LAS FLORES",
                "dm_cod" => "0428",
                "cod_mun" => "28",
                "department_id" => 4,
            ],
            [
                "id" => 129,
                "municipality_name" => "San Luis del Carmen",
                "mun_min" => "San Luis del Carmen",
                "mun_may" => "SAN LUIS DEL CARMEN",
                "dm_cod" => "0429",
                "cod_mun" => "29",
                "department_id" => 4,
            ],
            [
                "id" => 125,
                "municipality_name" => "San Miguel de Mercedes",
                "mun_min" => "San Miguel de Mercedes",
                "mun_may" => "SAN MIGUEL DE MERCEDES",
                "dm_cod" => "0430",
                "cod_mun" => "30",
                "department_id" => 4,
            ],
            [
                "id" => 87,
                "municipality_name" => "San Rafael",
                "mun_min" => "San Rafael",
                "mun_may" => "SAN RAFAEL",
                "dm_cod" => "0431",
                "cod_mun" => "31",
                "department_id" => 4,
            ],
            [
                "id" => 229,
                "municipality_name" => "Santa Rita",
                "mun_min" => "Santa Rita",
                "mun_may" => "SANTA RITA",
                "dm_cod" => "0432",
                "cod_mun" => "32",
                "department_id" => 4,
            ],
            [
                "id" => 100,
                "municipality_name" => "Tejutla",
                "mun_min" => "Tejutla",
                "mun_may" => "TEJUTLA",
                "dm_cod" => "0433",
                "cod_mun" => "33",
                "department_id" => 4,
            ],
            [
                "id" => 111,
                "municipality_name" => "Antiguo Cuscatlán",
                "mun_min" => "Antiguo Cuscatlan",
                "mun_may" => "ANTIGUO CUSCATLAN",
                "dm_cod" => "0501",
                "cod_mun" => "01",
                "department_id" => 5,
            ],
            [
                "id" => 130,
                "municipality_name" => "Ciudad Arce",
                "mun_min" => "Ciudad Arce",
                "mun_may" => "CIUDAD ARCE",
                "dm_cod" => "0502",
                "cod_mun" => "02",
                "department_id" => 5,
            ],
            [
                "id" => 43,
                "municipality_name" => "Colón",
                "mun_min" => "Colon",
                "mun_may" => "COLON",
                "dm_cod" => "0503",
                "cod_mun" => "03",
                "department_id" => 5,
            ],
            [
                "id" => 105,
                "municipality_name" => "Comasagua",
                "mun_min" => "Comasagua",
                "mun_may" => "COMASAGUA",
                "dm_cod" => "0504",
                "cod_mun" => "04",
                "department_id" => 5,
            ],
            [
                "id" => 95,
                "municipality_name" => "Chiltiupán",
                "mun_min" => "Chiltiupan",
                "mun_may" => "CHILTIUPAN",
                "dm_cod" => "0505",
                "cod_mun" => "05",
                "department_id" => 5,
            ],
            [
                "id" => 215,
                "municipality_name" => "Huizúcar",
                "mun_min" => "Huizucar",
                "mun_may" => "HUIZUCAR",
                "dm_cod" => "0506",
                "cod_mun" => "06",
                "department_id" => 5,
            ],
            [
                "id" => 99,
                "municipality_name" => "Jayaque",
                "mun_min" => "Jayaque",
                "mun_may" => "JAYAQUE",
                "dm_cod" => "0507",
                "cod_mun" => "07",
                "department_id" => 5,
            ],
            [
                "id" => 214,
                "municipality_name" => "Jicalapa",
                "mun_min" => "Jicalapa",
                "mun_may" => "JICALAPA",
                "dm_cod" => "0508",
                "cod_mun" => "08",
                "department_id" => 5,
            ],
            [
                "id" => 73,
                "municipality_name" => "La Libertad",
                "mun_min" => "La Libertad",
                "mun_may" => "LA LIBERTAD",
                "dm_cod" => "0509",
                "cod_mun" => "09",
                "department_id" => 5,
            ],
            [
                "id" => 96,
                "municipality_name" => "Nuevo Cuscatlán",
                "mun_min" => "Nuevo Cuscatlan",
                "mun_may" => "NUEVO CUSCATLAN",
                "dm_cod" => "0510",
                "cod_mun" => "10",
                "department_id" => 5,
            ],
            [
                "id" => 104,
                "municipality_name" => "Santa Tecla",
                "mun_min" => "Santa Tecla",
                "mun_may" => "SANTA TECLA",
                "dm_cod" => "0511",
                "cod_mun" => "11",
                "department_id" => 5,
            ],
            [
                "id" => 139,
                "municipality_name" => "Quezaltepeque",
                "mun_min" => "Quezaltepeque",
                "mun_may" => "QUEZALTEPEQUE",
                "dm_cod" => "0512",
                "cod_mun" => "12",
                "department_id" => 5,
            ],
            [
                "id" => 114,
                "municipality_name" => "Sacacoyo",
                "mun_min" => "Sacacoyo",
                "mun_may" => "SACACOYO",
                "dm_cod" => "0513",
                "cod_mun" => "13",
                "department_id" => 5,
            ],
            [
                "id" => 227,
                "municipality_name" => "San José Villanueva",
                "mun_min" => "San Jose Villanueva",
                "mun_may" => "SAN JOSE VILLANUEVA",
                "dm_cod" => "0514",
                "cod_mun" => "14",
                "department_id" => 5,
            ],
            [
                "id" => 103,
                "municipality_name" => "San Juan Opico",
                "mun_min" => "San Juan Opico",
                "mun_may" => "SAN JUAN OPICO",
                "dm_cod" => "0515",
                "cod_mun" => "15",
                "department_id" => 5,
            ],
            [
                "id" => 140,
                "municipality_name" => "San Matías",
                "mun_min" => "San Matias",
                "mun_may" => "SAN MATIAS",
                "dm_cod" => "0516",
                "cod_mun" => "16",
                "department_id" => 5,
            ],
            [
                "id" => 142,
                "municipality_name" => "San Pablo Tacachico",
                "mun_min" => "San Pablo Tacachico",
                "mun_may" => "SAN PABLO TACACHICO",
                "dm_cod" => "0517",
                "cod_mun" => "17",
                "department_id" => 5,
            ],
            [
                "id" => 18,
                "municipality_name" => "Tamanique",
                "mun_min" => "Tamanique",
                "mun_may" => "TAMANIQUE",
                "dm_cod" => "0518",
                "cod_mun" => "18",
                "department_id" => 5,
            ],
            [
                "id" => 17,
                "municipality_name" => "Talnique",
                "mun_min" => "Talnique",
                "mun_may" => "TALNIQUE",
                "dm_cod" => "0519",
                "cod_mun" => "19",
                "department_id" => 5,
            ],
            [
                "id" => 137,
                "municipality_name" => "Teotepeque",
                "mun_min" => "Teotepeque",
                "mun_may" => "TEOTEPEQUE",
                "dm_cod" => "0520",
                "cod_mun" => "20",
                "department_id" => 5,
            ],
            [
                "id" => 2,
                "municipality_name" => "Tepecoyo",
                "mun_min" => "Tepecoyo",
                "mun_may" => "TEPECOYO",
                "dm_cod" => "0521",
                "cod_mun" => "21",
                "department_id" => 5,
            ],
            [
                "id" => 85,
                "municipality_name" => "Zaragoza",
                "mun_min" => "Zaragoza",
                "mun_may" => "ZARAGOZA",
                "dm_cod" => "0522",
                "cod_mun" => "22",
                "department_id" => 5,
            ],
            [
                "id" => 213,
                "municipality_name" => "Aguilares",
                "mun_min" => "Aguilares",
                "mun_may" => "AGUILARES",
                "dm_cod" => "0601",
                "cod_mun" => "01",
                "department_id" => 6,
            ],
            [
                "id" => 24,
                "municipality_name" => "Apopa",
                "mun_min" => "Apopa",
                "mun_may" => "APOPA",
                "dm_cod" => "0602",
                "cod_mun" => "02",
                "department_id" => 6,
            ],
            [
                "id" => 48,
                "municipality_name" => "Ayutuxtepeque",
                "mun_min" => "Ayutuxtepeque",
                "mun_may" => "AYUTUXTEPEQUE",
                "dm_cod" => "0603",
                "cod_mun" => "03",
                "department_id" => 6,
            ],
            [
                "id" => 46,
                "municipality_name" => "Cuscatancingo",
                "mun_min" => "Cuscatancingo",
                "mun_may" => "CUSCATANCINGO",
                "dm_cod" => "0604",
                "cod_mun" => "04",
                "department_id" => 6,
            ],
            [
                "id" => 69,
                "municipality_name" => "El Paisnal",
                "mun_min" => "El Paisnal",
                "mun_may" => "EL PAISNAL",
                "dm_cod" => "0605",
                "cod_mun" => "05",
                "department_id" => 6,
            ],
            [
                "id" => 52,
                "municipality_name" => "Guazapa",
                "mun_min" => "Guazapa",
                "mun_may" => "GUAZAPA",
                "dm_cod" => "0606",
                "cod_mun" => "06",
                "department_id" => 6,
            ],
            [
                "id" => 29,
                "municipality_name" => "Ilopango",
                "mun_min" => "Ilopango",
                "mun_may" => "ILOPANGO",
                "dm_cod" => "0607",
                "cod_mun" => "07",
                "department_id" => 6,
            ],
            [
                "id" => 30,
                "municipality_name" => "Mejicanos",
                "mun_min" => "Mejicanos",
                "mun_may" => "MEJICANOS",
                "dm_cod" => "0608",
                "cod_mun" => "08",
                "department_id" => 6,
            ],
            [
                "id" => 66,
                "municipality_name" => "Nejapa",
                "mun_min" => "Nejapa",
                "mun_may" => "NEJAPA",
                "dm_cod" => "0609",
                "cod_mun" => "09",
                "department_id" => 6,
            ],
            [
                "id" => 6,
                "municipality_name" => "Panchimalco",
                "mun_min" => "Panchimalco",
                "mun_may" => "PANCHIMALCO",
                "dm_cod" => "0610",
                "cod_mun" => "10",
                "department_id" => 6,
            ],
            [
                "id" => 27,
                "municipality_name" => "Rosario de Mora",
                "mun_min" => "Rosario de Mora",
                "mun_may" => "ROSARIO DE MORA",
                "dm_cod" => "0611",
                "cod_mun" => "11",
                "department_id" => 6,
            ],
            [
                "id" => 9,
                "municipality_name" => "San Marcos",
                "mun_min" => "San Marcos",
                "mun_may" => "SAN MARCOS",
                "dm_cod" => "0612",
                "cod_mun" => "12",
                "department_id" => 6,
            ],
            [
                "id" => 12,
                "municipality_name" => "San Martín",
                "mun_min" => "San Martin",
                "mun_may" => "SAN MARTIN",
                "dm_cod" => "0613",
                "cod_mun" => "13",
                "department_id" => 6,
            ],
            [
                "id" => 4,
                "municipality_name" => "San Salvador",
                "mun_min" => "San Salvador",
                "mun_may" => "SAN SALVADOR",
                "dm_cod" => "0614",
                "cod_mun" => "14",
                "department_id" => 6,
            ],
            [
                "id" => 21,
                "municipality_name" => "Santiago Texacuangos",
                "mun_min" => "Santiago Texacuangos",
                "mun_may" => "SANTIAGO TEXACUANGOS",
                "dm_cod" => "0615",
                "cod_mun" => "15",
                "department_id" => 6,
            ],
            [
                "id" => 25,
                "municipality_name" => "Santo Tomás",
                "mun_min" => "Santo Tomas",
                "mun_may" => "SANTO TOMAS",
                "dm_cod" => "0616",
                "cod_mun" => "16",
                "department_id" => 6,
            ],
            [
                "id" => 7,
                "municipality_name" => "Soyapango",
                "mun_min" => "Soyapango",
                "mun_may" => "SOYAPANGO",
                "dm_cod" => "0617",
                "cod_mun" => "17",
                "department_id" => 6,
            ],
            [
                "id" => 67,
                "municipality_name" => "Tonacatepeque",
                "mun_min" => "Tonacatepeque",
                "mun_may" => "TONACATEPEQUE",
                "dm_cod" => "0618",
                "cod_mun" => "18",
                "department_id" => 6,
            ],
            [
                "id" => 22,
                "municipality_name" => "Ciudad Delgado",
                "mun_min" => "Ciudad Delgado",
                "mun_may" => "CIUDAD DELGADO",
                "dm_cod" => "0619",
                "cod_mun" => "19",
                "department_id" => 6,
            ],
            [
                "id" => 51,
                "municipality_name" => "Candelaria",
                "mun_min" => "Candelaria",
                "mun_may" => "CANDELARIA",
                "dm_cod" => "0701",
                "cod_mun" => "01",
                "department_id" => 7,
            ],
            [
                "id" => 16,
                "municipality_name" => "Cojutepeque",
                "mun_min" => "Cojutepeque",
                "mun_may" => "COJUTEPEQUE",
                "dm_cod" => "0702",
                "cod_mun" => "02",
                "department_id" => 7,
            ],
            [
                "id" => 32,
                "municipality_name" => "El Carmen",
                "mun_min" => "El Carmen",
                "mun_may" => "EL CARMEN",
                "dm_cod" => "0703",
                "cod_mun" => "03",
                "department_id" => 7,
            ],
            [
                "id" => 80,
                "municipality_name" => "El Rosario",
                "mun_min" => "El Rosario",
                "mun_may" => "EL ROSARIO",
                "dm_cod" => "0704",
                "cod_mun" => "04",
                "department_id" => 7,
            ],
            [
                "id" => 34,
                "municipality_name" => "Monte San Juan",
                "mun_min" => "Monte San Juan",
                "mun_may" => "MONTE SAN JUAN",
                "dm_cod" => "0705",
                "cod_mun" => "05",
                "department_id" => 7,
            ],
            [
                "id" => 74,
                "municipality_name" => "Oratorio de Concepción",
                "mun_min" => "Oratorio de Concepcion",
                "mun_may" => "ORATORIO DE CONCEPCION",
                "dm_cod" => "0706",
                "cod_mun" => "06",
                "department_id" => 7,
            ],
            [
                "id" => 39,
                "municipality_name" => "San Bartolomé Perulapía",
                "mun_min" => "San Bartolome Perulapia",
                "mun_may" => "SAN BARTOLOME PERULAPIA",
                "dm_cod" => "0707",
                "cod_mun" => "07",
                "department_id" => 7,
            ],
            [
                "id" => 71,
                "municipality_name" => "San Cristóbal",
                "mun_min" => "San Cristobal",
                "mun_may" => "SAN CRISTOBAL",
                "dm_cod" => "0708",
                "cod_mun" => "08",
                "department_id" => 7,
            ],
            [
                "id" => 31,
                "municipality_name" => "San José Guayabal",
                "mun_min" => "San Jose Guayabal",
                "mun_may" => "SAN JOSE GUAYABAL",
                "dm_cod" => "0709",
                "cod_mun" => "09",
                "department_id" => 7,
            ],
            [
                "id" => 218,
                "municipality_name" => "San Pedro Perulapán",
                "mun_min" => "San Pedro Perulapan",
                "mun_may" => "SAN PEDRO PERULAPAN",
                "dm_cod" => "0710",
                "cod_mun" => "10",
                "department_id" => 7,
            ],
            [
                "id" => 84,
                "municipality_name" => "San Rafael Cedros",
                "mun_min" => "San Rafael Cedros",
                "mun_may" => "SAN RAFAEL CEDROS",
                "dm_cod" => "0711",
                "cod_mun" => "11",
                "department_id" => 7,
            ],
            [
                "id" => 72,
                "municipality_name" => "San Ramón",
                "mun_min" => "San Ramon",
                "mun_may" => "SAN RAMON",
                "dm_cod" => "0712",
                "cod_mun" => "12",
                "department_id" => 7,
            ],
            [
                "id" => 81,
                "municipality_name" => "Santa Cruz Analquito",
                "mun_min" => "Santa Cruz Analquito",
                "mun_may" => "SANTA CRUZ ANALQUITO",
                "dm_cod" => "0713",
                "cod_mun" => "13",
                "department_id" => 7,
            ],
            [
                "id" => 82,
                "municipality_name" => "Santa Cruz Michapa",
                "mun_min" => "Santa Cruz Michapa",
                "mun_may" => "SANTA CRUZ MICHAPA",
                "dm_cod" => "0714",
                "cod_mun" => "14",
                "department_id" => 7,
            ],
            [
                "id" => 219,
                "municipality_name" => "Suchitoto",
                "mun_min" => "Suchitoto",
                "mun_may" => "SUCHITOTO",
                "dm_cod" => "0715",
                "cod_mun" => "15",
                "department_id" => 7,
            ],
            [
                "id" => 33,
                "municipality_name" => "Tenancingo",
                "mun_min" => "Tenancingo",
                "mun_may" => "TENANCINGO",
                "dm_cod" => "0716",
                "cod_mun" => "16",
                "department_id" => 7,
            ],
            [
                "id" => 154,
                "municipality_name" => "Cuyultitán",
                "mun_min" => "Cuyultitan",
                "mun_may" => "CUYULTITAN",
                "dm_cod" => "0801",
                "cod_mun" => "01",
                "department_id" => 8,
            ],
            [
                "id" => 106,
                "municipality_name" => "El Rosario",
                "mun_min" => "El Rosario",
                "mun_may" => "EL ROSARIO",
                "dm_cod" => "0802",
                "cod_mun" => "02",
                "department_id" => 8,
            ],
            [
                "id" => 236,
                "municipality_name" => "Jerusalén",
                "mun_min" => "Jerusalen",
                "mun_may" => "JERUSALEN",
                "dm_cod" => "0803",
                "cod_mun" => "03",
                "department_id" => 8,
            ],
            [
                "id" => 153,
                "municipality_name" => "Mercedes La Ceiba",
                "mun_min" => "Mercedes la Ceiba",
                "mun_may" => "MERCEDES LA CEIBA",
                "dm_cod" => "0804",
                "cod_mun" => "04",
                "department_id" => 8,
            ],
            [
                "id" => 147,
                "municipality_name" => "Olocuilta",
                "mun_min" => "Olocuilta",
                "mun_may" => "OLOCUILTA",
                "dm_cod" => "0805",
                "cod_mun" => "05",
                "department_id" => 8,
            ],
            [
                "id" => 145,
                "municipality_name" => "Paraíso de Osorio",
                "mun_min" => "Paraiso de Osorio",
                "mun_may" => "PARAISO DE OSORIO",
                "dm_cod" => "0806",
                "cod_mun" => "06",
                "department_id" => 8,
            ],
            [
                "id" => 115,
                "municipality_name" => "San Antonio Masahuat",
                "mun_min" => "San Antonio Masahuat",
                "mun_may" => "SAN ANTONIO MASAHUAT",
                "dm_cod" => "0807",
                "cod_mun" => "07",
                "department_id" => 8,
            ],
            [
                "id" => 116,
                "municipality_name" => "San Emigdio",
                "mun_min" => "San Emigdio",
                "mun_may" => "SAN EMIGDIO",
                "dm_cod" => "0808",
                "cod_mun" => "08",
                "department_id" => 8,
            ],
            [
                "id" => 126,
                "municipality_name" => "San Francisco Chinameca",
                "mun_min" => "San Francisco Chinameca",
                "mun_may" => "SAN FRANCISCO CHINAMECA",
                "dm_cod" => "0809",
                "cod_mun" => "09",
                "department_id" => 8,
            ],
            [
                "id" => 135,
                "municipality_name" => "San Juan Nonualco",
                "mun_min" => "San Juan Nonualco",
                "mun_may" => "SAN JUAN NONUALCO",
                "dm_cod" => "0810",
                "cod_mun" => "10",
                "department_id" => 8,
            ],
            [
                "id" => 150,
                "municipality_name" => "San Juan Talpa",
                "mun_min" => "San Juan Talpa",
                "mun_may" => "SAN JUAN TALPA",
                "dm_cod" => "0811",
                "cod_mun" => "11",
                "department_id" => 8,
            ],
            [
                "id" => 226,
                "municipality_name" => "San Juan Tepezontes",
                "mun_min" => "San Juan Tepezontes",
                "mun_may" => "SAN JUAN TEPEZONTES",
                "dm_cod" => "0812",
                "cod_mun" => "12",
                "department_id" => 8,
            ],
            [
                "id" => 143,
                "municipality_name" => "San Luis Talpa",
                "mun_min" => "San Luis Talpa",
                "mun_may" => "SAN LUIS TALPA",
                "dm_cod" => "0813",
                "cod_mun" => "13",
                "department_id" => 8,
            ],
            [
                "id" => 152,
                "municipality_name" => "San Miguel Tepezontes",
                "mun_min" => "San Miguel Tepezontes",
                "mun_may" => "SAN MIGUEL TEPEZONTES",
                "dm_cod" => "0814",
                "cod_mun" => "14",
                "department_id" => 8,
            ],
            [
                "id" => 151,
                "municipality_name" => "San Pedro Masahuat",
                "mun_min" => "San Pedro Masahuat",
                "mun_may" => "SAN PEDRO MASAHUAT",
                "dm_cod" => "0815",
                "cod_mun" => "15",
                "department_id" => 8,
            ],
            [
                "id" => 216,
                "municipality_name" => "San Pedro Nonualco",
                "mun_min" => "San Pedro Nonualco",
                "mun_may" => "SAN PEDRO NONUALCO",
                "dm_cod" => "0816",
                "cod_mun" => "16",
                "department_id" => 8,
            ],
            [
                "id" => 133,
                "municipality_name" => "San Rafael Obrajuelo",
                "mun_min" => "San Rafael Obrajuelo",
                "mun_may" => "SAN RAFAEL OBRAJUELO",
                "dm_cod" => "0817",
                "cod_mun" => "17",
                "department_id" => 8,
            ],
            [
                "id" => 76,
                "municipality_name" => "Santa María Ostuma",
                "mun_min" => "Santa Maria Ostuma",
                "mun_may" => "SANTA MARIA OSTUMA",
                "dm_cod" => "0818",
                "cod_mun" => "18",
                "department_id" => 8,
            ],
            [
                "id" => 144,
                "municipality_name" => "Santiago Nonualco",
                "mun_min" => "Santiago Nonualco",
                "mun_may" => "SANTIAGO NONUALCO",
                "dm_cod" => "0819",
                "cod_mun" => "19",
                "department_id" => 8,
            ],
            [
                "id" => 47,
                "municipality_name" => "Tapalhuaca",
                "mun_min" => "Tapalhuaca",
                "mun_may" => "TAPALHUACA",
                "dm_cod" => "0820",
                "cod_mun" => "20",
                "department_id" => 8,
            ],
            [
                "id" => 131,
                "municipality_name" => "Zacatecoluca",
                "mun_min" => "Zacatecoluca",
                "mun_may" => "ZACATECOLUCA",
                "dm_cod" => "0821",
                "cod_mun" => "21",
                "department_id" => 8,
            ],
            [
                "id" => 132,
                "municipality_name" => "San Luis La Herradura",
                "mun_min" => "San Luis la Herradura",
                "mun_may" => "SAN LUIS LA HERRADURA",
                "dm_cod" => "0822",
                "cod_mun" => "22",
                "department_id" => 8,
            ],
            [
                "id" => 158,
                "municipality_name" => "Cinquera",
                "mun_min" => "Cinquera",
                "mun_may" => "CINQUERA",
                "dm_cod" => "0901",
                "cod_mun" => "01",
                "department_id" => 9,
            ],
            [
                "id" => 239,
                "municipality_name" => "Guacotecti",
                "mun_min" => "Guacotecti",
                "mun_may" => "GUACOTECTI",
                "dm_cod" => "0902",
                "cod_mun" => "02",
                "department_id" => 9,
            ],
            [
                "id" => 157,
                "municipality_name" => "Ilobasco",
                "mun_min" => "Ilobasco",
                "mun_may" => "ILOBASCO",
                "dm_cod" => "0903",
                "cod_mun" => "03",
                "department_id" => 9,
            ],
            [
                "id" => 240,
                "municipality_name" => "Jutiapa",
                "mun_min" => "Jutiapa",
                "mun_may" => "JUTIAPA",
                "dm_cod" => "0904",
                "cod_mun" => "04",
                "department_id" => 9,
            ],
            [
                "id" => 44,
                "municipality_name" => "San Isidro",
                "mun_min" => "San Isidro",
                "mun_may" => "SAN ISIDRO",
                "dm_cod" => "0905",
                "cod_mun" => "05",
                "department_id" => 9,
            ],
            [
                "id" => 262,
                "municipality_name" => "Sensuntepeque",
                "mun_min" => "Sensuntepeque",
                "mun_may" => "SENSUNTEPEQUE",
                "dm_cod" => "0906",
                "cod_mun" => "06",
                "department_id" => 9,
            ],
            [
                "id" => 155,
                "municipality_name" => "Tejutepeque",
                "mun_min" => "Tejutepeque",
                "mun_may" => "TEJUTEPEQUE",
                "dm_cod" => "0907",
                "cod_mun" => "07",
                "department_id" => 9,
            ],
            [
                "id" => 159,
                "municipality_name" => "Victoria",
                "mun_min" => "Victoria",
                "mun_may" => "VICTORIA",
                "dm_cod" => "0908",
                "cod_mun" => "08",
                "department_id" => 9,
            ],
            [
                "id" => 161,
                "municipality_name" => "Dolores",
                "mun_min" => "Dolores",
                "mun_may" => "DOLORES",
                "dm_cod" => "0909",
                "cod_mun" => "09",
                "department_id" => 9,
            ],
            [
                "id" => 164,
                "municipality_name" => "Apastepeque",
                "mun_min" => "Apastepeque",
                "mun_may" => "APASTEPEQUE",
                "dm_cod" => "1001",
                "cod_mun" => "01",
                "department_id" => 10,
            ],
            [
                "id" => 167,
                "municipality_name" => "Guadalupe",
                "mun_min" => "Guadalupe",
                "mun_may" => "GUADALUPE",
                "dm_cod" => "1002",
                "cod_mun" => "02",
                "department_id" => 10,
            ],
            [
                "id" => 138,
                "municipality_name" => "San Cayetano Istepeque",
                "mun_min" => "San Cayetano Istepeque",
                "mun_may" => "SAN CAYETANO ISTEPEQUE",
                "dm_cod" => "1003",
                "cod_mun" => "03",
                "department_id" => 10,
            ],
            [
                "id" => 141,
                "municipality_name" => "Santa Clara",
                "mun_min" => "Santa Clara",
                "mun_may" => "SANTA CLARA",
                "dm_cod" => "1004",
                "cod_mun" => "04",
                "department_id" => 10,
            ],
            [
                "id" => 168,
                "municipality_name" => "Santo Domingo",
                "mun_min" => "Santo Domingo",
                "mun_may" => "SANTO DOMINGO",
                "dm_cod" => "1005",
                "cod_mun" => "05",
                "department_id" => 10,
            ],
            [
                "id" => 237,
                "municipality_name" => "San Esteban Catarina",
                "mun_min" => "San Esteban Catarina",
                "mun_may" => "SAN ESTEBAN CATARINA",
                "dm_cod" => "1006",
                "cod_mun" => "06",
                "department_id" => 10,
            ],
            [
                "id" => 134,
                "municipality_name" => "San Ildefonso",
                "mun_min" => "San Ildefonso",
                "mun_may" => "SAN ILDEFONSO",
                "dm_cod" => "1007",
                "cod_mun" => "07",
                "department_id" => 10,
            ],
            [
                "id" => 169,
                "municipality_name" => "San Lorenzo",
                "mun_min" => "San Lorenzo",
                "mun_may" => "SAN LORENZO",
                "dm_cod" => "1008",
                "cod_mun" => "08",
                "department_id" => 10,
            ],
            [
                "id" => 146,
                "municipality_name" => "San Sebastián",
                "mun_min" => "San Sebastian",
                "mun_may" => "SAN SEBASTIAN",
                "dm_cod" => "1009",
                "cod_mun" => "09",
                "department_id" => 10,
            ],
            [
                "id" => 165,
                "municipality_name" => "San Vicente",
                "mun_min" => "San Vicente",
                "mun_may" => "SAN VICENTE",
                "dm_cod" => "1010",
                "cod_mun" => "10",
                "department_id" => 10,
            ],
            [
                "id" => 166,
                "municipality_name" => "Tecoluca",
                "mun_min" => "Tecoluca",
                "mun_may" => "TECOLUCA",
                "dm_cod" => "1011",
                "cod_mun" => "11",
                "department_id" => 10,
            ],
            [
                "id" => 78,
                "municipality_name" => "Tepetitán",
                "mun_min" => "Tepetitan",
                "mun_may" => "TEPETITAN",
                "dm_cod" => "1012",
                "cod_mun" => "12",
                "department_id" => 10,
            ],
            [
                "id" => 234,
                "municipality_name" => "Verapaz",
                "mun_min" => "Verapaz",
                "mun_may" => "VERAPAZ",
                "dm_cod" => "1013",
                "cod_mun" => "13",
                "department_id" => 10,
            ],
            [
                "id" => 180,
                "municipality_name" => "Alegría",
                "mun_min" => "Alegria",
                "mun_may" => "ALEGRIA",
                "dm_cod" => "1101",
                "cod_mun" => "01",
                "department_id" => 11,
            ],
            [
                "id" => 45,
                "municipality_name" => "Berlín",
                "mun_min" => "Berlin",
                "mun_may" => "BERLIN",
                "dm_cod" => "1102",
                "cod_mun" => "02",
                "department_id" => 11,
            ],
            [
                "id" => 242,
                "municipality_name" => "California",
                "mun_min" => "California",
                "mun_may" => "CALIFORNIA",
                "dm_cod" => "1103",
                "cod_mun" => "03",
                "department_id" => 11,
            ],
            [
                "id" => 57,
                "municipality_name" => "Concepción Batres",
                "mun_min" => "Concepcion Batres",
                "mun_may" => "CONCEPCION BATRES",
                "dm_cod" => "1104",
                "cod_mun" => "04",
                "department_id" => 11,
            ],
            [
                "id" => 241,
                "municipality_name" => "El Triunfo",
                "mun_min" => "El Triunfo",
                "mun_may" => "EL TRIUNFO",
                "dm_cod" => "1105",
                "cod_mun" => "05",
                "department_id" => 11,
            ],
            [
                "id" => 55,
                "municipality_name" => "Ereguayquín",
                "mun_min" => "Ereguayquin",
                "mun_may" => "EREGUAYQUIN",
                "dm_cod" => "1106",
                "cod_mun" => "06",
                "department_id" => 11,
            ],
            [
                "id" => 249,
                "municipality_name" => "Estanzuelas",
                "mun_min" => "Estanzuelas",
                "mun_may" => "ESTANZUELAS",
                "dm_cod" => "1107",
                "cod_mun" => "07",
                "department_id" => 11,
            ],
            [
                "id" => 170,
                "municipality_name" => "Jiquilisco",
                "mun_min" => "Jiquilisco",
                "mun_may" => "JIQUILISCO",
                "dm_cod" => "1108",
                "cod_mun" => "08",
                "department_id" => 11,
            ],
            [
                "id" => 246,
                "municipality_name" => "Jucuapa",
                "mun_min" => "Jucuapa",
                "mun_may" => "JUCUAPA",
                "dm_cod" => "1109",
                "cod_mun" => "09",
                "department_id" => 11,
            ],
            [
                "id" => 149,
                "municipality_name" => "Jucuarán",
                "mun_min" => "Jucuaran",
                "mun_may" => "JUCUARAN",
                "dm_cod" => "1110",
                "cod_mun" => "10",
                "department_id" => 11,
            ],
            [
                "id" => 248,
                "municipality_name" => "Mercedes Umaña",
                "mun_min" => "Mercedes Umaña",
                "mun_may" => "MERCEDES UMAÑA",
                "dm_cod" => "1111",
                "cod_mun" => "11",
                "department_id" => 11,
            ],
            [
                "id" => 247,
                "municipality_name" => "Nueva Granada",
                "mun_min" => "Nueva Granada",
                "mun_may" => "NUEVA GRANADA",
                "dm_cod" => "1112",
                "cod_mun" => "12",
                "department_id" => 11,
            ],
            [
                "id" => 172,
                "municipality_name" => "Ozatlán",
                "mun_min" => "Ozatlan",
                "mun_may" => "OZATLAN",
                "dm_cod" => "1113",
                "cod_mun" => "13",
                "department_id" => 11,
            ],
            [
                "id" => 171,
                "municipality_name" => "Puerto El Triunfo",
                "mun_min" => "Puerto el Triunfo",
                "mun_may" => "PUERTO EL TRIUNFO",
                "dm_cod" => "1114",
                "cod_mun" => "14",
                "department_id" => 11,
            ],
            [
                "id" => 56,
                "municipality_name" => "San Agustín",
                "mun_min" => "San Agustin",
                "mun_may" => "SAN AGUSTIN",
                "dm_cod" => "1115",
                "cod_mun" => "15",
                "department_id" => 11,
            ],
            [
                "id" => 60,
                "municipality_name" => "San Buena Ventura",
                "mun_min" => "San Buena Ventura",
                "mun_may" => "SAN BUENA VENTURA",
                "dm_cod" => "1116",
                "cod_mun" => "16",
                "department_id" => 11,
            ],
            [
                "id" => 228,
                "municipality_name" => "San Dionisio",
                "mun_min" => "San Dionisio",
                "mun_may" => "SAN DIONISIO",
                "dm_cod" => "1117",
                "cod_mun" => "17",
                "department_id" => 11,
            ],
            [
                "id" => 162,
                "municipality_name" => "Santa Elena",
                "mun_min" => "Santa Elena",
                "mun_may" => "SANTA ELENA",
                "dm_cod" => "1118",
                "cod_mun" => "18",
                "department_id" => 11,
            ],
            [
                "id" => 173,
                "municipality_name" => "San Francisco Javier",
                "mun_min" => "San Francisco Javier",
                "mun_may" => "SAN FRANCISCO JAVIER",
                "dm_cod" => "1119",
                "cod_mun" => "19",
                "department_id" => 11,
            ],
            [
                "id" => 163,
                "municipality_name" => "Santa María",
                "mun_min" => "Santa Maria",
                "mun_may" => "SANTA MARIA",
                "dm_cod" => "1120",
                "cod_mun" => "20",
                "department_id" => 11,
            ],
            [
                "id" => 59,
                "municipality_name" => "Santiago de María",
                "mun_min" => "Santiago de Maria",
                "mun_may" => "SANTIAGO DE MARIA",
                "dm_cod" => "1121",
                "cod_mun" => "21",
                "department_id" => 11,
            ],
            [
                "id" => 178,
                "municipality_name" => "Tecapán",
                "mun_min" => "Tecapan",
                "mun_may" => "TECAPAN",
                "dm_cod" => "1122",
                "cod_mun" => "22",
                "department_id" => 11,
            ],
            [
                "id" => 148,
                "municipality_name" => "Usulután",
                "mun_min" => "Usulutan",
                "mun_may" => "USULUTAN",
                "dm_cod" => "1123",
                "cod_mun" => "23",
                "department_id" => 11,
            ],
            [
                "id" => 184,
                "municipality_name" => "Carolina",
                "mun_min" => "Carolina",
                "mun_may" => "CAROLINA",
                "dm_cod" => "1201",
                "cod_mun" => "01",
                "department_id" => 12,
            ],
            [
                "id" => 190,
                "municipality_name" => "Ciudad Barrios",
                "mun_min" => "Ciudad Barrios",
                "mun_may" => "CIUDAD BARRIOS",
                "dm_cod" => "1202",
                "cod_mun" => "02",
                "department_id" => 12,
            ],
            [
                "id" => 175,
                "municipality_name" => "Comacarán",
                "mun_min" => "Comacaran",
                "mun_may" => "COMACARAN",
                "dm_cod" => "1203",
                "cod_mun" => "03",
                "department_id" => 12,
            ],
            [
                "id" => 160,
                "municipality_name" => "Chapeltique",
                "mun_min" => "Chapeltique",
                "mun_may" => "CHAPELTIQUE",
                "dm_cod" => "1204",
                "cod_mun" => "04",
                "department_id" => 12,
            ],
            [
                "id" => 193,
                "municipality_name" => "Chinameca",
                "mun_min" => "Chinameca",
                "mun_may" => "CHINAMECA",
                "dm_cod" => "1205",
                "cod_mun" => "05",
                "department_id" => 12,
            ],
            [
                "id" => 251,
                "municipality_name" => "Chirilagua",
                "mun_min" => "Chirilagua",
                "mun_may" => "CHIRILAGUA",
                "dm_cod" => "1206",
                "cod_mun" => "06",
                "department_id" => 12,
            ],
            [
                "id" => 252,
                "municipality_name" => "El Tránsito",
                "mun_min" => "El Transito",
                "mun_may" => "EL TRANSITO",
                "dm_cod" => "1207",
                "cod_mun" => "07",
                "department_id" => 12,
            ],
            [
                "id" => 185,
                "municipality_name" => "Lolotique",
                "mun_min" => "Lolotique",
                "mun_may" => "LOLOTIQUE",
                "dm_cod" => "1208",
                "cod_mun" => "08",
                "department_id" => 12,
            ],
            [
                "id" => 191,
                "municipality_name" => "Moncagua",
                "mun_min" => "Moncagua",
                "mun_may" => "MONCAGUA",
                "dm_cod" => "1209",
                "cod_mun" => "09",
                "department_id" => 12,
            ],
            [
                "id" => 194,
                "municipality_name" => "Nueva Guadalupe",
                "mun_min" => "Nueva Guadalupe",
                "mun_may" => "NUEVA GUADALUPE",
                "dm_cod" => "1210",
                "cod_mun" => "10",
                "department_id" => 12,
            ],
            [
                "id" => 182,
                "municipality_name" => "Nuevo Edén de San Juan",
                "mun_min" => "Nuevo Eden de San Juan",
                "mun_may" => "NUEVO EDEN DE SAN JUAN",
                "dm_cod" => "1211",
                "cod_mun" => "11",
                "department_id" => 12,
            ],
            [
                "id" => 181,
                "municipality_name" => "Quelepa",
                "mun_min" => "Quelepa",
                "mun_may" => "QUELEPA",
                "dm_cod" => "1212",
                "cod_mun" => "12",
                "department_id" => 12,
            ],
            [
                "id" => 112,
                "municipality_name" => "San Antonio",
                "mun_min" => "San Antonio",
                "mun_may" => "SAN ANTONIO",
                "dm_cod" => "1213",
                "cod_mun" => "13",
                "department_id" => 12,
            ],
            [
                "id" => 174,
                "municipality_name" => "San Gerardo",
                "mun_min" => "San Gerardo",
                "mun_may" => "SAN GERARDO",
                "dm_cod" => "1214",
                "cod_mun" => "14",
                "department_id" => 12,
            ],
            [
                "id" => 156,
                "municipality_name" => "San Jorge",
                "mun_min" => "San Jorge",
                "mun_may" => "SAN JORGE",
                "dm_cod" => "1215",
                "cod_mun" => "15",
                "department_id" => 12,
            ],
            [
                "id" => 183,
                "municipality_name" => "San Luis de la Reina",
                "mun_min" => "San Luis de la Reina",
                "mun_may" => "SAN LUIS DE LA REINA",
                "dm_cod" => "1216",
                "cod_mun" => "16",
                "department_id" => 12,
            ],
            [
                "id" => 254,
                "municipality_name" => "San Miguel",
                "mun_min" => "San Miguel",
                "mun_may" => "SAN MIGUEL",
                "dm_cod" => "1217",
                "cod_mun" => "17",
                "department_id" => 12,
            ],
            [
                "id" => 189,
                "municipality_name" => "San Rafael Oriente",
                "mun_min" => "San Rafael Oriente",
                "mun_may" => "SAN RAFAEL ORIENTE",
                "dm_cod" => "1218",
                "cod_mun" => "18",
                "department_id" => 12,
            ],
            [
                "id" => 253,
                "municipality_name" => "Sesori",
                "mun_min" => "Sesori",
                "mun_may" => "SESORI",
                "dm_cod" => "1219",
                "cod_mun" => "19",
                "department_id" => 12,
            ],
            [
                "id" => 176,
                "municipality_name" => "Uluazapa",
                "mun_min" => "Uluazapa",
                "mun_may" => "ULUAZAPA",
                "dm_cod" => "1220",
                "cod_mun" => "20",
                "department_id" => 12,
            ],
            [
                "id" => 257,
                "municipality_name" => "Arambala",
                "mun_min" => "Arambala",
                "mun_may" => "ARAMBALA",
                "dm_cod" => "1301",
                "cod_mun" => "01",
                "department_id" => 13,
            ],
            [
                "id" => 86,
                "municipality_name" => "Cacaopera",
                "mun_min" => "Cacaopera",
                "mun_may" => "CACAOPERA",
                "dm_cod" => "1302",
                "cod_mun" => "02",
                "department_id" => 13,
            ],
            [
                "id" => 188,
                "municipality_name" => "Corinto",
                "mun_min" => "Corinto",
                "mun_may" => "CORINTO",
                "dm_cod" => "1303",
                "cod_mun" => "03",
                "department_id" => 13,
            ],
            [
                "id" => 186,
                "municipality_name" => "Chilanga",
                "mun_min" => "Chilanga",
                "mun_may" => "CHILANGA",
                "dm_cod" => "1304",
                "cod_mun" => "04",
                "department_id" => 13,
            ],
            [
                "id" => 202,
                "municipality_name" => "Delicias de Concepción",
                "mun_min" => "Delicias de Concepcion",
                "mun_may" => "DELICIAS DE CONCEPCION",
                "dm_cod" => "1305",
                "cod_mun" => "05",
                "department_id" => 13,
            ],
            [
                "id" => 200,
                "municipality_name" => "El Divisadero",
                "mun_min" => "El Divisadero",
                "mun_may" => "EL DIVISADERO",
                "dm_cod" => "1306",
                "cod_mun" => "06",
                "department_id" => 13,
            ],
            [
                "id" => 256,
                "municipality_name" => "El Rosario",
                "mun_min" => "El Rosario",
                "mun_may" => "EL ROSARIO",
                "dm_cod" => "1307",
                "cod_mun" => "07",
                "department_id" => 13,
            ],
            [
                "id" => 243,
                "municipality_name" => "Gualococti",
                "mun_min" => "Gualococti",
                "mun_may" => "GUALOCOCTI",
                "dm_cod" => "1308",
                "cod_mun" => "08",
                "department_id" => 13,
            ],
            [
                "id" => 250,
                "municipality_name" => "Guatajiagua",
                "mun_min" => "Guatajiagua",
                "mun_may" => "GUATAJIAGUA",
                "dm_cod" => "1309",
                "cod_mun" => "09",
                "department_id" => 13,
            ],
            [
                "id" => 235,
                "municipality_name" => "Joateca",
                "mun_min" => "Joateca",
                "mun_may" => "JOATECA",
                "dm_cod" => "1310",
                "cod_mun" => "10",
                "department_id" => 13,
            ],
            [
                "id" => 258,
                "municipality_name" => "Jocoaitique",
                "mun_min" => "Jocoaitique",
                "mun_may" => "JOCOAITIQUE",
                "dm_cod" => "1311",
                "cod_mun" => "11",
                "department_id" => 13,
            ],
            [
                "id" => 259,
                "municipality_name" => "Jocoro",
                "mun_min" => "Jocoro",
                "mun_may" => "JOCORO",
                "dm_cod" => "1312",
                "cod_mun" => "12",
                "department_id" => 13,
            ],
            [
                "id" => 196,
                "municipality_name" => "Lolotiquillo",
                "mun_min" => "Lolotiquillo",
                "mun_may" => "LOLOTIQUILLO",
                "dm_cod" => "1313",
                "cod_mun" => "13",
                "department_id" => 13,
            ],
            [
                "id" => 260,
                "municipality_name" => "Meanguera",
                "mun_min" => "Meanguera",
                "mun_may" => "MEANGUERA",
                "dm_cod" => "1314",
                "cod_mun" => "14",
                "department_id" => 13,
            ],
            [
                "id" => 201,
                "municipality_name" => "Osicala",
                "mun_min" => "Osicala",
                "mun_may" => "OSICALA",
                "dm_cod" => "1315",
                "cod_mun" => "15",
                "department_id" => 13,
            ],
            [
                "id" => 195,
                "municipality_name" => "Perquín",
                "mun_min" => "Perquin",
                "mun_may" => "PERQUIN",
                "dm_cod" => "1316",
                "cod_mun" => "16",
                "department_id" => 13,
            ],
            [
                "id" => 199,
                "municipality_name" => "San Carlos",
                "mun_min" => "San Carlos",
                "mun_may" => "SAN CARLOS",
                "dm_cod" => "1317",
                "cod_mun" => "17",
                "department_id" => 13,
            ],
            [
                "id" => 261,
                "municipality_name" => "San Fernando",
                "mun_min" => "San Fernando",
                "mun_may" => "SAN FERNANDO",
                "dm_cod" => "1318",
                "cod_mun" => "18",
                "department_id" => 13,
            ],
            [
                "id" => 255,
                "municipality_name" => "San Francisco Gotera",
                "mun_min" => "San Francisco Gotera",
                "mun_may" => "SAN FRANCISCO GOTERA",
                "dm_cod" => "1319",
                "cod_mun" => "19",
                "department_id" => 13,
            ],
            [
                "id" => 198,
                "municipality_name" => "San Isidro",
                "mun_min" => "San Isidro",
                "mun_may" => "SAN ISIDRO",
                "dm_cod" => "1320",
                "cod_mun" => "20",
                "department_id" => 13,
            ],
            [
                "id" => 197,
                "municipality_name" => "San Simón",
                "mun_min" => "San Simon",
                "mun_may" => "SAN SIMON",
                "dm_cod" => "1321",
                "cod_mun" => "21",
                "department_id" => 13,
            ],
            [
                "id" => 177,
                "municipality_name" => "Sensembra",
                "mun_min" => "Sensembra",
                "mun_may" => "SENSEMBRA",
                "dm_cod" => "1322",
                "cod_mun" => "22",
                "department_id" => 13,
            ],
            [
                "id" => 187,
                "municipality_name" => "Sociedad",
                "mun_min" => "Sociedad",
                "mun_may" => "SOCIEDAD",
                "dm_cod" => "1323",
                "cod_mun" => "23",
                "department_id" => 13,
            ],
            [
                "id" => 192,
                "municipality_name" => "Torola",
                "mun_min" => "Torola",
                "mun_may" => "TOROLA",
                "dm_cod" => "1324",
                "cod_mun" => "24",
                "department_id" => 13,
            ],
            [
                "id" => 245,
                "municipality_name" => "Yamabal",
                "mun_min" => "Yamabal",
                "mun_may" => "YAMABAL",
                "dm_cod" => "1325",
                "cod_mun" => "25",
                "department_id" => 13,
            ],
            [
                "id" => 179,
                "municipality_name" => "Yoloaiquín",
                "mun_min" => "Yoloaiquin",
                "mun_may" => "YOLOAIQUIN",
                "dm_cod" => "1326",
                "cod_mun" => "26",
                "department_id" => 13,
            ],
            [
                "id" => 208,
                "municipality_name" => "Anamorós",
                "mun_min" => "Anamoros",
                "mun_may" => "ANAMOROS",
                "dm_cod" => "1401",
                "cod_mun" => "01",
                "department_id" => 14,
            ],
            [
                "id" => 128,
                "municipality_name" => "Bolívar",
                "mun_min" => "Bolivar",
                "mun_may" => "BOLIVAR",
                "dm_cod" => "1402",
                "cod_mun" => "02",
                "department_id" => 14,
            ],
            [
                "id" => 209,
                "municipality_name" => "Concepción de Oriente",
                "mun_min" => "Concepcion de Oriente",
                "mun_may" => "CONCEPCION DE ORIENTE",
                "dm_cod" => "1403",
                "cod_mun" => "03",
                "department_id" => 14,
            ],
            [
                "id" => 244,
                "municipality_name" => "Conchagua",
                "mun_min" => "Conchagua",
                "mun_may" => "CONCHAGUA",
                "dm_cod" => "1404",
                "cod_mun" => "04",
                "department_id" => 14,
            ],
            [
                "id" => 238,
                "municipality_name" => "El Carmen",
                "mun_min" => "El Carmen",
                "mun_may" => "EL CARMEN",
                "dm_cod" => "1405",
                "cod_mun" => "05",
                "department_id" => 14,
            ],
            [
                "id" => 110,
                "municipality_name" => "El Sauce",
                "mun_min" => "El Sauce",
                "mun_may" => "EL SAUCE",
                "dm_cod" => "1406",
                "cod_mun" => "06",
                "department_id" => 14,
            ],
            [
                "id" => 203,
                "municipality_name" => "Intipucá",
                "mun_min" => "Intipuca",
                "mun_may" => "INTIPUCA",
                "dm_cod" => "1407",
                "cod_mun" => "07",
                "department_id" => 14,
            ],
            [
                "id" => 58,
                "municipality_name" => "La Unión",
                "mun_min" => "La Union",
                "mun_may" => "LA UNION",
                "dm_cod" => "1408",
                "cod_mun" => "08",
                "department_id" => 14,
            ],
            [
                "id" => 211,
                "municipality_name" => "Lislique",
                "mun_min" => "Lislique",
                "mun_may" => "LISLIQUE",
                "dm_cod" => "1409",
                "cod_mun" => "09",
                "department_id" => 14,
            ],
            [
                "id" => 109,
                "municipality_name" => "Meanguera del Golfo",
                "mun_min" => "Meanguera del Golfo",
                "mun_may" => "MEANGUERA DEL GOLFO",
                "dm_cod" => "1410",
                "cod_mun" => "10",
                "department_id" => 14,
            ],
            [
                "id" => 210,
                "municipality_name" => "Nueva Esparta",
                "mun_min" => "Nueva Esparta",
                "mun_may" => "NUEVA ESPARTA",
                "dm_cod" => "1411",
                "cod_mun" => "11",
                "department_id" => 14,
            ],
            [
                "id" => 204,
                "municipality_name" => "Pasaquina",
                "mun_min" => "Pasaquina",
                "mun_may" => "PASAQUINA",
                "dm_cod" => "1412",
                "cod_mun" => "12",
                "department_id" => 14,
            ],
            [
                "id" => 212,
                "municipality_name" => "Polorós",
                "mun_min" => "Poloros",
                "mun_may" => "POLOROS",
                "dm_cod" => "1413",
                "cod_mun" => "13",
                "department_id" => 14,
            ],
            [
                "id" => 205,
                "municipality_name" => "San Alejo",
                "mun_min" => "San Alejo",
                "mun_may" => "SAN ALEJO",
                "dm_cod" => "1414",
                "cod_mun" => "14",
                "department_id" => 14,
            ],
            [
                "id" => 108,
                "municipality_name" => "San José",
                "mun_min" => "San Jose",
                "mun_may" => "SAN JOSE",
                "dm_cod" => "1415",
                "cod_mun" => "15",
                "department_id" => 14,
            ],
            [
                "id" => 206,
                "municipality_name" => "Santa Rosa de Lima",
                "mun_min" => "Santa Rosa de Lima",
                "mun_may" => "SANTA ROSA DE LIMA",
                "dm_cod" => "1416",
                "cod_mun" => "16",
                "department_id" => 14,
            ],
            [
                "id" => 136,
                "municipality_name" => "Yayantique",
                "mun_min" => "Yayantique",
                "mun_may" => "YAYANTIQUE",
                "dm_cod" => "1417",
                "cod_mun" => "17",
                "department_id" => 14,
            ],
            [
                "id" => 207,
                "municipality_name" => "Yucuaiquín",
                "mun_min" => "Yucuaiquin",
                "mun_may" => "YUCUAIQUIN",
                "dm_cod" => "1418",
                "cod_mun" => "18",
                "department_id" => 14,
            ],
        ]);
    }
}
